/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FornecedorDAO;
import dao.UsuarioDAO;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import net.proteanit.sql.DbUtils;
import utils.ConnectionFactory;


/**
 *
 * @author Camila
 */
public class CadastroFornecedores extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClientes
     */
    public CadastroFornecedores() {
        conexao = ConnectionFactory.conector(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        //JFrame frame = new JFrame("CadastroClientes");
        //frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        txtTelefoneFornecedor = new javax.swing.JTextField();
        txtEmailFornecedor = new javax.swing.JTextField();
        txtEnderecoFornecedor = new javax.swing.JTextField();
        txtCpfCnpjFornecedor = new javax.swing.JTextField();
        btnLimparFornecedor = new javax.swing.JButton();
        btnSalvarFornecedor = new javax.swing.JButton();
        btnAlterarFornecedor = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblEndereco1 = new javax.swing.JLabel();
        rbAtivo = new javax.swing.JRadioButton();
        rbInativo = new javax.swing.JRadioButton();
        lbl = new javax.swing.JLabel();
        lblOperador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modulo de Fornecedores");
        setResizable(false);

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Endereço", "CPF/CNPJ", "Telefone", "Email", "Ativo"
            }
        ));
        tblFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFornecedores);

        lblNome.setText("Fornecedor");

        lblCelular.setText("Telefone");

        lblEmail.setText("Email");

        lblEndereco.setText("Endereço");

        lblCpf.setText("CPF/CNPJ");

        txtNomeFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomeFornecedorKeyReleased(evt);
            }
        });

        btnLimparFornecedor.setText("Limpar");
        btnLimparFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFornecedorActionPerformed(evt);
            }
        });

        btnSalvarFornecedor.setText("Incluir");
        btnSalvarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFornecedorActionPerformed(evt);
            }
        });

        btnAlterarFornecedor.setText("Editar");
        btnAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFornecedorActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblEndereco1.setText("Status");
        lblEndereco1.setToolTipText("");

        buttonGroup1.add(rbAtivo);
        rbAtivo.setSelected(true);
        rbAtivo.setText("Ativo");

        buttonGroup1.add(rbInativo);
        rbInativo.setText("Inativo");

        lbl.setText("Usuário:");

        lblOperador.setText("usuario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnLimparFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvarFornecedor)
                        .addGap(101, 101, 101)
                        .addComponent(btnAlterarFornecedor)
                        .addGap(80, 80, 80)
                        .addComponent(btnSair)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblCelular)
                            .addComponent(lblEmail)
                            .addComponent(lblEndereco)
                            .addComponent(lblCpf)
                            .addComponent(lblEndereco1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEnderecoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                            .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefoneFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCpfCnpjFornecedor)
                            .addComponent(rbInativo)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rbAtivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl)
                                .addGap(18, 18, 18)
                                .addComponent(lblOperador)
                                .addGap(70, 70, 70)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelular)
                    .addComponent(txtTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpfCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbAtivo)
                            .addComponent(lbl)
                            .addComponent(lblOperador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbInativo)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEndereco1)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparFornecedor)
                    .addComponent(btnSalvarFornecedor)
                    .addComponent(btnAlterarFornecedor)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedoresMouseClicked
        // TODO add your handling code here:
        setCamposFornecedor();
    }//GEN-LAST:event_tblFornecedoresMouseClicked

    private void txtNomeFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeFornecedorKeyReleased
        try {
            // TODO add your handling code here:
            pesquisarFornecedor();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtNomeFornecedorKeyReleased

    private void btnLimparFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFornecedorActionPerformed
        // TODO add your handling code here:
        limpaTelaFornecedor();
    }//GEN-LAST:event_btnLimparFornecedorActionPerformed

    private void btnSalvarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFornecedorActionPerformed
        // TODO add your handling code here:
        UsuarioDAO usuarioDao = new UsuarioDAO();
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        int verificaPerfil = 0;
        try {
            verificaPerfil = usuarioDao.verificaPerfil(lblOperador.getText());
        } catch (SQLException ex) {
            Logger.getLogger(CadastroFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (verificaPerfil == 1) {
            if (txtNomeFornecedor.getText().equals("") || txtTelefoneFornecedor.getText().equals("(  )      -    ") || txtEmailFornecedor.getText().equals("") || txtEnderecoFornecedor.getText().equals("") || txtCpfCnpjFornecedor.getText().equals("   .   .   -  ")) {
                JOptionPane.showMessageDialog(null, "Existem campos vazios");
            } else {
                try {
                    //salvarCliente();
                    fornecedorDAO.salvarFornecedor(txtNomeFornecedor.getText(),txtEnderecoFornecedor.getText(),txtCpfCnpjFornecedor.getText(),txtTelefoneFornecedor.getText(),txtEmailFornecedor.getText(),rbAtivo.isSelected(),rbInativo.isSelected());
                } catch (SQLException ex) {
                    Logger.getLogger(CadastroFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                }
                limpaTelaFornecedor();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Perfil não autorizado para essa transação", "Erro", JOptionPane.ERROR_MESSAGE);
            limpaTelaFornecedor();
        }
    }//GEN-LAST:event_btnSalvarFornecedorActionPerformed

    private void btnAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFornecedorActionPerformed
        // TODO add your handling code here:
        UsuarioDAO usuarioDao = new UsuarioDAO();
        FornecedorDAO fornecedorDAO = new FornecedorDAO();
        int verificaPerfil = 0;
        try {
            verificaPerfil = usuarioDao.verificaPerfil(lblOperador.getText());
        } catch (SQLException ex) {
            Logger.getLogger(CadastroFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (verificaPerfil == 1 || verificaPerfil == 2) {
            int question = JOptionPane.showConfirmDialog(null, "Deseja Salvar as alterações?", "Atenção", JOptionPane.YES_NO_OPTION);
            if (txtNomeFornecedor.getText().equals("") || txtEnderecoFornecedor.getText().equals("") || txtTelefoneFornecedor.getText().equals("") || txtCpfCnpjFornecedor.getText().equals("") || txtEmailFornecedor.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos");
            } else {
                if (question == JOptionPane.YES_OPTION) {
                    try {
                        //alterarCliente();
                        fornecedorDAO.alterarFornecedor(txtNomeFornecedor.getText(),txtEnderecoFornecedor.getText(),txtTelefoneFornecedor.getText(),txtEmailFornecedor.getText(),txtCpfCnpjFornecedor.getText(), rbAtivo.isSelected(),rbInativo.isSelected());
                    } catch (SQLException ex) {
                        Logger.getLogger(CadastroFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    limpaTelaFornecedor();
                    try {
                        pesquisarFornecedor();
                    } catch (SQLException ex) {
                        Logger.getLogger(CadastroFornecedores.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Nenhuma alteração foi realizada.", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Perfil não autorizado para essa transação", "Erro", JOptionPane.ERROR_MESSAGE);
            limpaTelaFornecedor();
        }
    }//GEN-LAST:event_btnAlterarFornecedorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedores().setVisible(true);
            }
        });
    }
    
    private void limpaTelaFornecedor() {
        txtNomeFornecedor.setText(null);
        txtTelefoneFornecedor.setText(null);
        txtCpfCnpjFornecedor.setText(null);
        txtEmailFornecedor.setText(null);
        txtEnderecoFornecedor.setText(null);
        //txtIdCliente.setText(null);
        DefaultTableModel model = (DefaultTableModel) tblFornecedores.getModel();
        model.setRowCount(0);
    }
    
    public void pesquisarFornecedor() throws SQLException {
        conexao = ConnectionFactory.conector(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        String sql = "select * from fornecedores where nome like ? ORDER BY nome ASC";
        //String sql = "select * from clientes where nome like ? and ativo = true";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtNomeFornecedor.getText() + "%");
            rs = pst.executeQuery();

            tblFornecedores.setModel(DbUtils.resultSetToTableModel(rs));
            conexao.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            conexao.close();
        }

    }
    
    private void setCamposFornecedor() {
        int setar = tblFornecedores.getSelectedRow();
        //txtIdCliente.setText(tblClientes.getModel().getValueAt(setar, 0).toString());
        txtNomeFornecedor.setText(tblFornecedores.getModel().getValueAt(setar, 0).toString());
        txtEnderecoFornecedor.setText(tblFornecedores.getModel().getValueAt(setar, 1).toString());
        txtCpfCnpjFornecedor.setText(tblFornecedores.getModel().getValueAt(setar, 2).toString());
        txtTelefoneFornecedor.setText(tblFornecedores.getModel().getValueAt(setar, 3).toString());
        txtEmailFornecedor.setText(tblFornecedores.getModel().getValueAt(setar, 4).toString());
        if(tblFornecedores.getValueAt(setar, 5).equals(true)){
            rbAtivo.setSelected(true);
        }
        if(tblFornecedores.getValueAt(setar, 5).equals(false)){
            rbInativo.setSelected(true);
        }
    }
    
    void exportarNome(Cliente usuario) {
        lblOperador.setText(usuario.getNome());
        //lbl.setText(usuario.getNome());
    }
    
    //JLabel lblFoto = new JLabel("Foto");
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    private JTable table;
    private String caminhoFoto;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarFornecedor;
    private javax.swing.JButton btnLimparFornecedor;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarFornecedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEndereco1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblOperador;
    public javax.swing.JRadioButton rbAtivo;
    public javax.swing.JRadioButton rbInativo;
    private javax.swing.JTable tblFornecedores;
    public javax.swing.JTextField txtCpfCnpjFornecedor;
    public javax.swing.JTextField txtEmailFornecedor;
    public javax.swing.JTextField txtEnderecoFornecedor;
    public javax.swing.JTextField txtNomeFornecedor;
    public javax.swing.JTextField txtTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
